#!/usr/bin/env python3
import sys
import os

# Ajoutez le répertoire courant au PYTHONPATH
sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__))))

# Importez et exécutez la fonction main du module cloudya.cli
try:
    from cloudya.cli import main
    main()
except ImportError as e:
    print(f"Erreur d'importation : {e}")
    print(f"PYTHONPATH actuel : {sys.path}")
    sys.exit(1)
